### ISSUE TITLE
What the fuck is this

### ISSUE THREAD

**Issue by ghost** [storiku/instahack#4]
So I took a look at the code, not to run it because im not a skid and

![image](https://user-images.githubusercontent.com/52085196/87846958-51401e80-c8d4-11ea-8358-b60ede93bb9c.png)
what the shit

**Comment by robbyoconnor** [comment]
People will still run it

**Comment by yezz123** [comment]
🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by harrisrussels** [comment]
:laughing: :laughing: :laughing:
